In [13]:
import pandas as pd
import numpy as np

In [2]:
df_books = pd.read_csv('/content/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv')

In [3]:
df_books.head(2)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

## Drop columns

In [4]:
df_books.drop('Genre', axis=1).head(2) # 1 referente a columnas 0 a filas

,Name,Author,User Rating,Reviews,Price,Year
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011

para borrarlo directamente del dataframe

In [5]:
 df_books.drop('Genre', axis=1, inplace=True)
 df_books.head(2)

,Name,Author,User Rating,Reviews,Price,Year
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011

Otra opción

In [ ]:
df_books = df_books.drop('Year', axis=1)

In [6]:
df_books.head(2)

,Name,Author,User Rating,Reviews,Price,Year
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011

con del, función propia de python

In [7]:
del df_books['Price']

## Borrar columnas

In [8]:
df_books.head(2)

                            Name        Author  User Rating  Reviews  Year
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350  2016
1              11/22/63: A Novel  Stephen King          4.6     2052  2011

In [9]:
df_books.drop(0, axis=0).head(2)

,Name,Author,User Rating,Reviews,Year
1,11/22/63: A Novel,Stephen King,4.6,2052,2011
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,2018

In [10]:
df_books.drop([1,2,4], axis=0).head(2)

                            Name         Author  User Rating  Reviews  Year
0  10-Day Green Smoothie Cleanse       JJ Smith          4.7    17350  2016
3         1984 (Signet Classics)  George Orwell          4.7    21424  2017

In [11]:
df_books.drop(range(0,10), axis=0).head(2)

,Name,Author,User Rating,Reviews,Year
10,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,2017
11,A Patriot's History of the United States: From...,Larry Schweikart,4.6,460,2010

## Añadir columnas

In [12]:
df_books.head(3)

,Name,Author,User Rating,Reviews,Year
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,2016
1,11/22/63: A Novel,Stephen King,4.6,2052,2011
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,2018

In [14]:
df_books['Nueva_columna'] = np.nan
df_books.head(4)

,Name,Author,User Rating,Reviews,Year,Nueva_columna
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,2016,NaN
1,11/22/63: A Novel,Stephen King,4.6,2052,2011,NaN
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,2018,NaN
3,1984 (Signet Classics),George Orwell,4.7,21424,2017,NaN

In [15]:
df_books.shape[0]# filas

550

In [ ]:
data = np.arange(0, df_books.shape[0])
data

In [17]:
df_books['Rango'] = data

In [18]:
df_books.head(4)

,Name,Author,User Rating,Reviews,Year,Nueva_columna,Rango
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,2016,NaN,0
1,11/22/63: A Novel,Stephen King,4.6,2052,2011,NaN,1
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,2018,NaN,2
3,1984 (Signet Classics),George Orwell,4.7,21424,2017,NaN,3

## Agregar filas

In [19]:
df_books.append(df_books)

,Name,Author,User Rating,Reviews,Year,Nueva_columna,Rango
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,2016,NaN,0
1,11/22/63: A Novel,Stephen King,4.6,2052,2011,NaN,1
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,2018,NaN,2
3,1984 (Signet Classics),George Orwell,4.7,21424,2017,NaN,3
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,2019,NaN,4
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,2019,NaN,545
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,2016,NaN,546
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,2017,NaN,547
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,2018,NaN,548
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,2019,NaN,549