In [1]:
import pandas as pd

In [2]:
df_books = pd.read_csv('/content/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv')
df_books.head(2)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

In [4]:
df_books.groupby('Author').count()

                            Name  User Rating  Reviews  Price  Year  Genre
Author
Abraham Verghese               2            2        2      2     2      2
Adam Gasiewski                 1            1        1      1     1      1
Adam Mansbach                  1            1        1      1     1      1
Adir Levy                      1            1        1      1     1      1
Admiral William H. McRaven     1            1        1      1     1      1
...                          ...          ...      ...    ...   ...    ...
Walter Isaacson                3            3        3      3     3      3
William Davis                  2            2        2      2     2      2
William P. Young               2            2        2      2     2      2
Wizards RPG Team               3            3        3      3     3      3
Zhi Gang Sha                   2            2        2      2     2      2

[248 rows x 6 columns]

In [5]:
df_books.groupby('Author').max()

,Name,User Rating,Reviews,Price,Year,Genre
Author,,,,,,
Abraham Verghese,Cutting for Stone,4.6,4866,11,2011,Fiction
Adam Gasiewski,Milk and Vine: Inspirational Quotes From Class...,4.4,3113,6,2017,Non Fiction
Adam Mansbach,Go the F**k to Sleep,4.8,9568,9,2011,Fiction
Adir Levy,What Should Danny Do? (The Power to Choose Ser...,4.8,8170,13,2019,Fiction
Admiral William H. McRaven,Make Your Bed: Little Things That Can Change Y...,4.7,10199,11,2017,Non Fiction
...,...,...,...,...,...,...
Walter Isaacson,Steve Jobs,4.6,7827,21,2017,Non Fiction
William Davis,"Wheat Belly: Lose the Wheat, Lose the Weight, ...",4.4,7497,6,2013,Non Fiction
William P. Young,The Shack: Where Tragedy Confronts Eternity,4.6,19720,8,2017,Fiction
Wizards RPG Team,Player's Handbook (Dungeons & Dragons),4.8,16990,27,2019,Fiction
Zhi Gang Sha,Soul Healing Miracles: Ancient and New Sacred ...,4.6,220,17,2013,Non Fiction

In [6]:
df_books.groupby('Author').sum() # darse cuenta que se suman hasta los años
# autor pasa a ser el indice del dataframe

                            User Rating  Reviews  Price  Year
Author
Abraham Verghese                    9.2     9732     22  4021
Adam Gasiewski                      4.4     3113      6  2017
Adam Mansbach                       4.8     9568      9  2011
Adir Levy                           4.8     8170     13  2019
Admiral William H. McRaven          4.7    10199     11  2017
...                                 ...      ...    ...   ...
Walter Isaacson                    13.7    18668     61  6040
William Davis                       8.8    14994     12  4025
William P. Young                    9.2    39440     16  4026
Wizards RPG Team                   14.4    50970     81  6054
Zhi Gang Sha                        9.2      257     23  4022

[248 rows x 4 columns]

In [7]:
df_books.groupby('Author').sum().loc['William Davis']

User Rating        8.8
Reviews        14994.0
Price             12.0
Year            4025.0
Name: William Davis, dtype: float64

In [8]:
df_books.groupby('Author').sum().reset_index()

                         Author  User Rating  Reviews  Price  Year
0              Abraham Verghese          9.2     9732     22  4021
1                Adam Gasiewski          4.4     3113      6  2017
2                 Adam Mansbach          4.8     9568      9  2011
3                     Adir Levy          4.8     8170     13  2019
4    Admiral William H. McRaven          4.7    10199     11  2017
..                          ...          ...      ...    ...   ...
243             Walter Isaacson         13.7    18668     61  6040
244               William Davis          8.8    14994     12  4025
245            William P. Young          9.2    39440     16  4026
246            Wizards RPG Team         14.4    50970     81  6054
247                Zhi Gang Sha          9.2      257     23  4022

[248 rows x 5 columns]

In [9]:
df_books.groupby('Author').agg(['min','max'])# saca dos metricas diferentes a traves de
# agragacion

                                                                         Name  \
                                                                          min
Author
Abraham Verghese                                            Cutting for Stone
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...
Adam Mansbach                                            Go the F**k to Sleep
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...
...                                                                       ...
Walter Isaacson                                             Leonardo da Vinci
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...
William P. Young                  The Shack: Where Tragedy Confronts Eternity
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...

                                                                               \
                                                                          max
Author
Abraham Verghese                                            Cutting for Stone
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...
Adam Mansbach                                            Go the F**k to Sleep
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...
...                                                                       ...
Walter Isaacson                                                    Steve Jobs
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...
William P. Young                  The Shack: Where Tragedy Confronts Eternity
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...

                           User Rating      Reviews        Price      Year  \
                                   min  max     min    max   min max   min
Author
Abraham Verghese                   4.6  4.6    4866   4866    11  11  2010
Adam Gasiewski                     4.4  4.4    3113   3113     6   6  2017
Adam Mansbach                      4.8  4.8    9568   9568     9   9  2011
Adir Levy                          4.8  4.8    8170   8170    13  13  2019
Admiral William H. McRaven         4.7  4.7   10199  10199    11  11  2017
...                                ...  ...     ...    ...   ...  ..   ...
Walter Isaacson                    4.5  4.6    3014   7827    20  21  2011
William Davis                      4.4  4.4    7497   7497     6   6  2012
William P. Young                   4.6  4.6   19720  19720     8   8  2009
Wizards RPG Team                   4.8  4.8   16990  16990    27  27  2017
Zhi Gang Sha                       4.6  4.6      37    220     6  17  2009

                                        Genre
                             max          min          max
Author
Abraham Verghese            2011      Fiction      Fiction
Adam Gasiewski              2017  Non Fiction  Non Fiction
Adam Mansbach               2011      Fiction      Fiction
Adir Levy                   2019      Fiction      Fiction
Admiral William H. McRaven  2017  Non Fiction  Non Fiction
...                          ...          ...          ...
Walter Isaacson             2017  Non Fiction  Non Fiction
William Davis               2013  Non Fiction  Non Fiction
William P. Young            2017      Fiction      Fiction
Wizards RPG Team            2019      Fiction      Fiction
Zhi Gang Sha                2013  Non Fiction  Non Fiction

[248 rows x 12 columns]

In [10]:
df_books.head(2)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

In [12]:
df_books.groupby('Author').agg({'Reviews':['min', 'max'], 'User Rating': 'sum'})
# nos permite seleccionar columnas y las metricas de cada columna

                           Reviews        User Rating
                               min    max         sum
Author
Abraham Verghese              4866   4866         9.2
Adam Gasiewski                3113   3113         4.4
Adam Mansbach                 9568   9568         4.8
Adir Levy                     8170   8170         4.8
Admiral William H. McRaven   10199  10199         4.7
...                            ...    ...         ...
Walter Isaacson               3014   7827        13.7
William Davis                 7497   7497         8.8
William P. Young             19720  19720         9.2
Wizards RPG Team             16990  16990        14.4
Zhi Gang Sha                    37    220         9.2

[248 rows x 3 columns]

In [13]:
df_books.groupby(['Author', 'Year']).count()

                       Name  User Rating  Reviews  Price  Genre
Author           Year
Abraham Verghese 2010     1            1        1      1      1
                 2011     1            1        1      1      1
Adam Gasiewski   2017     1            1        1      1      1
Adam Mansbach    2011     1            1        1      1      1
Adir Levy        2019     1            1        1      1      1
...                     ...          ...      ...    ...    ...
Wizards RPG Team 2017     1            1        1      1      1
                 2018     1            1        1      1      1
                 2019     1            1        1      1      1
Zhi Gang Sha     2009     1            1        1      1      1
                 2013     1            1        1      1      1

[493 rows x 5 columns]